StylesPath = .vale/styles
MinAlertLevel = warning
Packages = Google
[*.adoc]
BasedOnStyles = Vale, Google, Capy
; AsciiDoc source/callout blocks are code, not prose:
BlockIgnores = (?s) *(\[source.*?----.*?----)
TokenIgnores = (\x60[^\x60]+\x60)
